import type { IconType } from "react-icons";
import {
  SiC,
  SiCplusplus,
  SiDotnet,
  SiDart,
  SiElixir,
  SiGnubash,
  SiGo,
  SiJavascript,
  SiKotlin,
  SiNodedotjs,
  SiOpenjdk,
  SiPhp,
  SiPython,
  SiRuby,
  SiRust,
  SiScala,
  SiSwift,
  SiTypescript,
} from "react-icons/si";
import {
  Brain,
  ChartLine,
  Cloud,
  Code,
  Database,
  EnvelopeSimple,
  HardDrives,
  Image,
  Key,
  MapPin,
  Megaphone,
  Package,
  ShieldCheck,
  TreeStructure,
  type Icon as PhosphorIcon,
} from "@phosphor-icons/react";
import type { CategoryId, LanguageId } from "../types/catalog";

export const languageIcons: Record<LanguageId, IconType> = {
  python: SiPython,
  javascript: SiJavascript,
  typescript: SiTypescript,
  nodejs: SiNodedotjs,
  go: SiGo,
  rust: SiRust,
  java: SiOpenjdk,
  kotlin: SiKotlin,
  swift: SiSwift,
  ruby: SiRuby,
  php: SiPhp,
  csharp: SiDotnet,
  dart: SiDart,
  cpp: SiCplusplus,
  c: SiC,
  scala: SiScala,
  elixir: SiElixir,
  shell: SiGnubash,
};

export const categoryIcons: Record<CategoryId, PhosphorIcon> = {
  ai: Brain,
  auth: Key,
  payments: Package,
  cloud: Cloud,
  database: Database,
  comms: Megaphone,
  analytics: ChartLine,
  storage: HardDrives,
  devtools: Code,
  observability: ChartLine,
  security: ShieldCheck,
  media: Image,
  maps: MapPin,
  email: EnvelopeSimple,
  infrastructure: TreeStructure,
};
